"use client";
import { Provider } from "react-redux";
import "./globals.css";
import { store } from "./Redux/Store";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "./Common/Navbar/Navbar";

export const metadata = {
  title: "Delhi Crime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
    </>
  );
}
