"use client";
import { Provider } from "react-redux";
import "./globals.css";
import { store } from "./Redux/Store";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Delhi Crime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <Provider store={store}>{children}</Provider>;
}
